export const WS_URL = `ws://localhost:8080/ws/game`

export const MessageType = {
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  ERROR: 'ERROR',
  PONG: 'PONG',

  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  ROOM_UPDATE: 'ROOM_UPDATE',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  PLAYER_READY: 'PLAYER_READY',

  START_GAME: 'START_GAME',
  GAME_START: 'GAME_START',
  GAME_END: 'GAME_END',
  GAME_STATE: 'GAME_STATE',

  DEAL_CARDS: 'DEAL_CARDS',
  COMMUNITY_CARDS: 'COMMUNITY_CARDS',

  NEW_ROUND: 'NEW_ROUND',
  YOUR_TURN: 'YOUR_TURN',
  PLAYER_ACTION: 'PLAYER_ACTION',
  ACTION_RESULT: 'ACTION_RESULT',

  PHASE_CHANGE: 'PHASE_CHANGE',
  FLOP: 'FLOP',
  TURN: 'TURN',
  RIVER: 'RIVER',
  SHOWDOWN: 'SHOWDOWN',
  SHOWDOWN_RESULT: 'SHOWDOWN_RESULT',

  ROUND_RESULT: 'ROUND_RESULT',
  POT_UPDATE: 'POT_UPDATE',

  CHAT: 'CHAT'
}